name: example
description: Example application.
version: 1.0.0+1
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  adaptive_dialog:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod:
  go_router:
  mono_kit:
  recase:
  simple_logger:
  url_launcher:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
dependency_overrides:
  adaptive_dialog:
    path: ..
flutter:
  uses-material-design: true
