name: example
description: Eample application.
version: 1.0.0+1
environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  adaptive_dialog:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  mono_kit:
  provider:
  recase:
  simple_logger:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
dependency_overrides:
  adaptive_dialog:
    path: ..
flutter:
  uses-material-design: true