name: example
description: Eample application.
version: 1.0.0+1
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  adaptive_dialog:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  mono_kit:
    git:
      url: https://github.com/mono0926/flutter_mono_kit
  provider: '>=5.0.0-0 <6.0.0'
  recase: '>=4.0.0-0 <5.0.0'
  simple_logger:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
dependency_overrides:
  adaptive_dialog:
    path: ..
  plugin_platform_interface: ^1.1.0-nullsafety.2
flutter:
  uses-material-design: true