name: adaptive_dialog
description: Show alert dialog or modal action sheet adaptively according to platform.
version: 1.4.0
homepage: https://github.com/mono0926/adaptive_dialog
environment:
  sdk: '>=2.15.0 <3.0.0'
dependencies:
  animations: '>=2.0.0 <3.0.0'
  collection: '>=1.15.0 <2.0.0'
  flutter:
    sdk: flutter
  meta: '>=1.3.0 <2.0.0'
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:
